# Use Node.js LTS version as base
FROM node:18

# Set working directory
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install all dependencies, including devDependencies
RUN npm install

# Copy the rest of the app files
COPY . .

RUN  npm install typescript

# Build TypeScript code using npx
RUN npx tsc

# Expose the port your app runs on
EXPOSE 8080

# Start the app from the compiled JavaScript in dist folder
CMD ["node", "dist/index.js"]
